FROM oven/bun:1

WORKDIR /app

COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json

COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN bun install

EXPOSE 3000

CMD [ "bun", "dev:frontend" ]
# d build -t quiz_fe -f ./docker/dev/Dockerfile.frontend .