FROM oven/bun:1

WORKDIR /app

ARG PUBLISHABLE_KEY

ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$PUBLISHABLE_KEY

COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN bun install
RUN bun run build:frontend

EXPOSE 3000

CMD ["bun", "start:frontend"]
# d build --build-arg PUBLISHABLE_KEY=<NEXT_PUBLIC> -t quiz_fe -f ./docker/Dockerfile.frontend .